--USE SQL_Practice3;
GO 

/*VIEW*/
CREATE VIEW DATA_1 AS
SELECT e.FIRST_NAME,i.INCENTIVE_AMOUNT  FROM Employee e JOIN Incentives i ON e.EMPLOYEE_ID=i.EMPLOYEE_REF_ID;
GO 

CREATE VIEW DATA_2 AS
SELECT DISTINCT e.FIRST_NAME FROM Employee e WHERE CHARINDEX('o',FIRST_NAME) <> 0;
GO

SELECT * FROM DATA_1;
SELECT * FROM DATA_2;
DROP VIEW DATA_1;
DROP VIEW DATA_2;

/*INDEXES*/
CREATE INDEX I1 ON Employee (Employee_ID,FIRST_NAME);
DROP INDEX Employee.I1;


/*STORED PROCEDURES*/
CREATE PROCEDURE p1
AS																			/*no PARAMETER AND WHERE*/
BEGIN 
SELECT FIRST_NAME FROM Employee;
END
EXEC p1;
GO


CREATE PROCEDURE p2(@depart VARCHAR(50))                                  /*Single PARAMETER AND WHERE*/
AS
BEGIN
SELECT FIRST_NAME,SALARY,DEPARTMENT FROM Employee
WHERE DEPARTMENT = @depart;
END
EXEC p2'Insurance';
GO


CREATE PROCEDURE p3(@depart VARCHAR(20),@salary INT)                      /*TWO PARAMETER AND WHERE*/
AS
BEGIN
SELECT e.EMPLOYEE_ID,e.FIRST_NAME FROM Employee e
WHERE e.DEPARTMENT = @depart AND e.SALARY > @salary;
END
EXEC p3 'Insurance','700000';
GO


CREATE or ALTER PROCEDURE p4(@depart VARCHAR(20),@salary INT)                       /*IF STATEMENT*/                 
AS
BEGIN
DECLARE @D VARCHAR(50);
DECLARE @S INT;
SELECT @D = e.DEPARTMENT FROM Employee e WHERE e.DEPARTMENT = @depart;
SELECT @S = e.SALARY FROM Employee e WHERE e.SALARY > @salary;

IF @depart = @D AND @S > @salary
BEGIN
SELECT ('ID: '+CAST(e.EMPLOYEE_ID as VARCHAR(10))+'NAME: '+e.FIRST_NAME) 'RECORD'  FROM Employee e
END
ELSE
BEGIN
PRINT 'NO RECORD FOUND';
END
END
EXEC p4'',700000;
DROP PROCEDURE p4;
GO


/*CASE*/
Select  e.EMPLOYEE_ID,e.FIRST_NAME,e.LAST_NAME,
case 
	when SALARY > 1000000  then '>1000000'
	when SALARY > 800000  then '>800000'
	WHEN SALARY > 700000 THEN '>700000'
	WHEN SALARY > 600000 THEN '>600000'
	else 'No' 
end AS 'MESSAGE'
FROM Employee e;
GO



CREATE OR ALTER PROCEDURE p5                                /*CASE with Procedure*/
AS
BEGIN
SELECT e.EMPLOYEE_ID,e.FIRST_NAME,e.LAST_NAME,
CASE 
	WHEN SALARY > 1000000 THEN '>1000000'
	WHEN SALARY > 800000 THEN '>800000'
	WHEN SALARY > 600000 THEN '>700000'
	ELSE 'NO'
END 'Message'
FROM Employee e;
END
EXEC p5;
GO


CREATE OR ALTER PROCEDURE p6(@a INT,@b INT,@c INT)                                /*CASE with Procedure and parameter*/
AS
BEGIN
SELECT e.EMPLOYEE_ID,e.FIRST_NAME,e.LAST_NAME,
CASE 
	WHEN SALARY > @a THEN '>1000000'
	WHEN SALARY > @b THEN '>800000'
	WHEN SALARY > @c THEN '>700000'
	ELSE 'NO'
END 'Message'
FROM Employee e;
END
EXEC p6 1000000,800000,700000;
GO



CREATE OR ALTER PROCEDURE p7(@a INT)                                /*CASE with Procedure and PASSING 1 value*/
AS
BEGIN
SELECT e.EMPLOYEE_ID,e.FIRST_NAME,e.LAST_NAME,
CASE 
	WHEN SALARY > 1000000 THEN '>1000000'
	WHEN SALARY > 800000 THEN '>800000'
	WHEN SALARY > 700000 THEN '>700000'
	ELSE 'NO'
END 'Message'
FROM Employee e WHERE e.EMPLOYEE_ID = @a;
END

--DECLARE @x INT;
--SELECT @x = e.EMPLOYEE_ID FROM Employee e;
EXEC p7 1;
GO


CREATE OR ALTER PROCEDURE p8(@a INT)                                /*CASE with Procedure and PASSING 1 value(ID,NULL,'')*/
AS
BEGIN
SELECT e.EMPLOYEE_ID,e.FIRST_NAME,e.LAST_NAME,
CASE 
	WHEN SALARY > 1000000 THEN '>1000000'
	WHEN SALARY > 800000 THEN '>800000'
	WHEN SALARY > 700000 THEN '>700000'
	WHEN SALARY > 600000 THEN '>600000'
	ELSE '<600000'
END 'Message'
FROM Employee e WHERE e.EMPLOYEE_ID = @a OR ISNULL(@a,'') = '' /*@a IS NULL*/ ;
END
EXEC p8 ' ';

/*ORDER BY CASE*/
SELECT * FROM Employee ORDER BY 
(CASE WHEN MANAGER_ID IS NULL THEN SALARY
END);